flowchart LR
            Pelanggan([Pelanggan])
            Admin([Admin])
            
            subgraph Sistem E-Commerce Pojok Jepara
                UC1(Login / Registrasi)
                UC2(Lihat Katalog & Stok Real-Time)
                UC3(Kelola Keranjang Belanja)
                UC4(Checkout & Pilih Metode Ambil)
                UC5(Lihat Riwayat Pesanan)
                
                UC6(Kelola Data Produk)
                UC7(Kelola Data Pesanan)
                UC8(Cetak Laporan Penjualan)
                UC9(Jalankan Algoritma K-Means)
            end
            
            Pelanggan --> UC1
            Pelanggan --> UC2
            Pelanggan --> UC3
            Pelanggan --> UC4
            Pelanggan --> UC5
            
            Admin --> UC1
            Admin --> UC6
            Admin --> UC7
            Admin --> UC8
            Admin --> UC9