flowchart TD
            A([Mulai]) --> B[Pelanggan Memilih Produk]
            B --> C{Cek Ketersediaan Stok}
            C -->|Stok Habis| D[Tampilkan Peringatan Habis]
            D --> B
            C -->|Stok Ada| E[Klik 'Tambah ke Keranjang']
            E --> F[Buka Halaman Keranjang]
            F --> G[Klik 'Checkout']
            G --> H[Pilih Metode Pembayaran & Pengambilan]
            H --> I[Konfirmasi Pesanan]
            I --> J[Sistem Mengunci Lock & Mengurangi Stok]
            J --> K([Selesai / Tampilkan Nomor Pesanan])